"""Write benchmarks/retrieval_products.yaml: product queries generated from the processed catalog.

Products are sampled across car types in proportion to their share (seeded, so the same catalog gives
the same file), and each is asked for in four styles; see product_queries in
src/tiredai/benchmarks/retrieval.py. The file is committed so the queries can be reviewed and stay
fixed between runs; regenerate it only when the catalog changes.

Usage:
    uv run python scripts/generate_retrieval_queries.py [--products N] [--seed N]
"""

import argparse

from tiredai.benchmarks.catalog import Catalog
from tiredai.benchmarks.experiments import BENCHMARKS_DIR
from tiredai.benchmarks.retrieval import product_queries, write_product_queries
from tiredai.config import Settings


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--products", type=int, default=40, help="products to sample (default: 40)")
    parser.add_argument("--seed", type=int, default=7)
    args = parser.parse_args()

    catalog = Catalog.load(Settings.load().processed_data_path)
    queries = product_queries(catalog, args.products, args.seed)
    path = BENCHMARKS_DIR / "retrieval_products.yaml"
    path.parent.mkdir(exist_ok=True)
    header = (f"Generated by scripts/generate_retrieval_queries.py --products {args.products} --seed {args.seed}; "
              "regenerate instead of editing.")  # fmt: skip
    write_product_queries(path, queries, header)
    print(f"Wrote {len(queries)} queries for {args.products} products to {path.relative_to(BENCHMARKS_DIR.parent)}")


if __name__ == "__main__":
    main()
